"""empty message

Revision ID: 38cf1731d2ae
Revises: 0001_gallery_init
Create Date: 2026-09-08 13:07:17.317526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '38cf1731d2ae'
down_revision: Union[str, None] = '0001_gallery_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('description_changed', sa.Boolean(),
                                        nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'description_changed')
    # ### end Alembic commands ###
